# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QR.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from unicodedata import name
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.pyplot import text 
import qrcode,os,shutil
from PIL import Image
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(0)
        global C_data 
        C_data="" 
        global pixmap 
        pixmap=""
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:rgb(0,0,60); \n"
"border-radius:10px;\n"
"}\n"
"QPushButton{ \n"
"color:white;  \n"
"background-color:transparent; \n"
"padding:10px 20px; \n"
"font: 14pt \"Poppins, sans-serif\"; \n"
"text-align:left; \n"
"margin-top:5px; \n"
"border-radius:6px;\n"
"} \n"
"QPushButton:hover{ \n"
" background-color:#0c0358; \n"
"\n"
"} \n"
"QLabel{  \n"
"font: 16pt \"Poppins, sans-serif\";  \n"
"padding:5px 10px; \n"
"color:white; \n"
"background-color:rgb(255, 170, 0) ;\n"
"border-radius:10px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("border-radius:5px;")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/cil-link-alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/cil-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/cil-text-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_6.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icon_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.pushButton_5)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(240, 240, 240)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setStyleSheet("QLabel{ \n"
"font: 21pt \"Poppins, sans-serif\"; \n"
"} \n"
"QLineEdit{  \n"
"border:2px solid black; \n"
"border-radius:5px; \n"
"padding:5px; \n"
"font: 14pt \"Poppins, sans-serif\"; \n"
"} \n"
"QPushButton{\n"
"padding:8px; \n"
"border:2px solid black;\n"
"font: 14pt \"Poppins, sans-serif\"; \n"
"} \n"
"QTextEdit{  \n"
"border:2px solid rgb(0,0,70); \n"
"border-radius:8px;\n"
"font: 14pt \"Poppins, sans-serif\"; \n"
"padding:2px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_15 = QtWidgets.QFrame(self.page)
        self.frame_15.setStyleSheet("")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.frame_15)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_9.addWidget(self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.verticalLayout_8.addWidget(self.frame_15)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_16 = QtWidgets.QFrame(self.page_2)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.label_8 = QtWidgets.QLabel(self.frame_16)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_11.addWidget(self.lineEdit_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem4)
        self.verticalLayout_10.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("QFrame{  \n"
"padding:5px; \n"
"font: 14pt \"Poppins, sans-serif\"; \n"
"}")
        self.page_4.setObjectName("page_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_18 = QtWidgets.QFrame(self.page_4)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem5 = QtWidgets.QSpacerItem(20, 203, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem5)
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.frame_19)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.horizontalSlider_version = QtWidgets.QSlider(self.frame_19)
        self.horizontalSlider_version.setMinimum(1)
        self.horizontalSlider_version.setMaximum(15)
        self.horizontalSlider_version.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_version.setObjectName("horizontalSlider_version")
        self.horizontalLayout_9.addWidget(self.horizontalSlider_version)
        self.label_13 = QtWidgets.QLabel(self.frame_19)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.verticalLayout_15.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.frame_20)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.horizontalSlider_2_border = QtWidgets.QSlider(self.frame_20)
        self.horizontalSlider_2_border.setMinimum(4)
        self.horizontalSlider_2_border.setMaximum(10)
        self.horizontalSlider_2_border.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2_border.setObjectName("horizontalSlider_2_border")
        self.horizontalLayout_10.addWidget(self.horizontalSlider_2_border)
        self.label_14 = QtWidgets.QLabel(self.frame_20)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.verticalLayout_15.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.frame_21)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.horizontalSlider_3_boxs = QtWidgets.QSlider(self.frame_21)
        self.horizontalSlider_3_boxs.setMinimum(5)
        self.horizontalSlider_3_boxs.setMaximum(10)
        self.horizontalSlider_3_boxs.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3_boxs.setObjectName("horizontalSlider_3_boxs")
        self.horizontalLayout_11.addWidget(self.horizontalSlider_3_boxs)
        self.label_15 = QtWidgets.QLabel(self.frame_21)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.verticalLayout_15.addWidget(self.frame_21)
        spacerItem6 = QtWidgets.QSpacerItem(20, 203, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem6)
        self.verticalLayout_14.addWidget(self.frame_18)
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_17 = QtWidgets.QFrame(self.page_3)
        self.frame_17.setStyleSheet("QPushButton:hover{ \n"
"     color:white;\n"
"    background-color: #383854; \n"
"    border:2px solid #383854;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.frame_17)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.textEdit = QtWidgets.QTextEdit(self.frame_17)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_13.addWidget(self.textEdit)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_13.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(460, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 59); \n"
"color:white; \n"
"border-radius:10px; \n"
"font: 14pt \"Poppins, sans-serif\";")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.QR_l = QtWidgets.QLabel(self.frame_5)
        self.QR_l.setObjectName("QR_l")
        self.horizontalLayout_7.addWidget(self.QR_l, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setStyleSheet("background-color: #0c0354")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_13)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.file_name_lineedit = QtWidgets.QLineEdit(self.frame_13)
        self.file_name_lineedit.setStyleSheet("QLineEdit{  \n"
"border:2px solid white; \n"
"border-radius:6px; \n"
"padding:2px;\n"
"}  \n"
"QLineEdit:hover{  \n"
"border:2px solid rgb(0, 85, 255) \n"
"}")
        self.file_name_lineedit.setObjectName("file_name_lineedit")
        self.horizontalLayout_4.addWidget(self.file_name_lineedit)
        self.verticalLayout_5.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_5.setSpacing(9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_12)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.file_location_lineedit = QtWidgets.QLineEdit(self.frame_12)
        self.file_location_lineedit.setStyleSheet("QLineEdit{  \n"
"border:2px solid white; \n"
"border-radius:6px; \n"
"padding:2px;\n"
"}  \n"
"QLineEdit:hover{  \n"
"border:2px solid rgb(0, 85, 255) \n"
"}")
        self.file_location_lineedit.setObjectName("file_location_lineedit")
        self.horizontalLayout_5.addWidget(self.file_location_lineedit)
        self.browse_btn = QtWidgets.QPushButton(self.frame_12)
        self.browse_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_btn.setStyleSheet("QPushButton{  \n"
"border:2px solid white ;\n"
"border-radius:6px; \n"
"padding:2px;\n"
"} \n"
"QPushButton:hover{ \n"
"background-color: rgb(255, 255, 255); \n"
"color:rgb(0, 0, 90);\n"
"}")
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout_5.addWidget(self.browse_btn)
        self.verticalLayout_5.addWidget(self.frame_12)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setStyleSheet("background-color:#0c0354;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.fill_lineedit = QtWidgets.QLineEdit(self.frame_11)
        self.fill_lineedit.setStyleSheet("QLineEdit{  \n"
"border:2px solid white; \n"
"border-radius:6px; \n"
"padding:2px;\n"
"}  \n"
"QLineEdit:hover{  \n"
"border:2px solid rgb(0, 85, 255) \n"
"}")
        self.fill_lineedit.setObjectName("fill_lineedit")
        self.horizontalLayout_3.addWidget(self.fill_lineedit)
        self.label_5 = QtWidgets.QLabel(self.frame_11)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.back_lineedit = QtWidgets.QLineEdit(self.frame_11)
        self.back_lineedit.setStyleSheet("QLineEdit{  \n"
"border:2px solid white; \n"
"border-radius:6px; \n"
"padding:2px;\n"
"}  \n"
"QLineEdit:hover{  \n"
"border:2px solid rgb(0, 85, 255) \n"
"}")
        self.back_lineedit.setObjectName("back_lineedit")
        self.horizontalLayout_3.addWidget(self.back_lineedit)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.apply_btn = QtWidgets.QPushButton(self.frame_10)
        self.apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apply_btn.setStyleSheet("QPushButton{  \n"
"border:2px solid white ;\n"
"border-radius:6px; \n"
"padding:3px 20px;\n"
"} \n"
"QPushButton:hover{ \n"
"background-color: rgb(255, 255, 255); \n"
"color:rgb(0, 0, 90);\n"
"}")
        self.apply_btn.setObjectName("apply_btn")
        self.verticalLayout_4.addWidget(self.apply_btn, 0, QtCore.Qt.AlignHCenter)
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_6.setSpacing(9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_14)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.logo_path_linedit = QtWidgets.QLineEdit(self.frame_14)
        self.logo_path_linedit.setStyleSheet("QLineEdit{  \n"
"border:2px solid white; \n"
"border-radius:6px; \n"
"padding:2px;\n"
"}  \n"
"QLineEdit:hover{  \n"
"border:2px solid rgb(0, 85, 255) ;\n"
"}")
        self.logo_path_linedit.setObjectName("logo_path_linedit")
        self.horizontalLayout_6.addWidget(self.logo_path_linedit)
        self.browse_logo_btn = QtWidgets.QPushButton(self.frame_14)
        self.browse_logo_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_logo_btn.setStyleSheet("QPushButton{  \n"
"border:2px solid white ;\n"
"border-radius:6px; \n"
"padding:2px;\n"
"} \n"
"QPushButton:hover{ \n"
"background-color: rgb(255, 255, 255); \n"
"color:rgb(0, 0, 90);\n"
"}")
        self.browse_logo_btn.setObjectName("browse_logo_btn")
        self.horizontalLayout_6.addWidget(self.browse_logo_btn)
        self.verticalLayout_4.addWidget(self.frame_14)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setStyleSheet("QRadioButton{  \n"
"border:2px solid white;\n"
"border-radius:5px; \n"
"color:white; \n"
"padding:5px 15px;\n"
"} \n"
"QRadioButton:hover{ \n"
"background-color:#160692;\n"
"}\n"
"QRadioButton:checked {\n"
"    background-color:#160692;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_png = QtWidgets.QRadioButton(self.frame_8)
        self.radio_png.setStyleSheet("")
        self.radio_png.setObjectName("radio_png")
        self.horizontalLayout_2.addWidget(self.radio_png, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.radio_jpg = QtWidgets.QRadioButton(self.frame_8)
        self.radio_jpg.setObjectName("radio_jpg")
        self.horizontalLayout_2.addWidget(self.radio_jpg, 0, QtCore.Qt.AlignHCenter)
        self.radio_svg = QtWidgets.QRadioButton(self.frame_8)
        self.radio_svg.setObjectName("radio_svg")
        self.horizontalLayout_2.addWidget(self.radio_svg, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_8, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignBottom)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_8.setSpacing(9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.savecode_btn = QtWidgets.QPushButton(self.frame_7)
        self.savecode_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.savecode_btn.setStyleSheet("QPushButton{  \n"
"border:2px solid transparent ;\n"
"border-radius:6px; \n"
"padding:2px 15px; \n"
"background-color: #5b51f2; \n"
"} \n"
"QPushButton:hover{ \n"
"background-color: rgb(255, 255, 255); \n"
"color:rgb(0, 0, 90);\n"
"}")
        self.savecode_btn.setObjectName("savecode_btn")
        self.horizontalLayout_8.addWidget(self.savecode_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow) 
        self.pushButton.clicked.connect(self.websitepage) 
        self.pushButton_2.clicked.connect(self.filecontent)  
        self.pushButton_3.clicked.connect(self.textmessage) 
        self.pushButton_5.clicked.connect(self.settings)  
        self.update_settings()
        self.horizontalSlider_2_border.valueChanged.connect(self.update_settings) 
        self.horizontalSlider_3_boxs.valueChanged.connect(self.update_settings)
        self.horizontalSlider_version.valueChanged.connect(self.update_settings)
        self.file_location_lineedit.setText(os.getcwd()) 
        self.radio_png.setChecked(1) 
        self.stackedWidget.setCurrentIndex(0)  
        pixmap=QtGui.QPixmap("down.png") 
        self.update_settings()
        self.QR_l.setPixmap(pixmap) 
        self.QR_l.setScaledContents(1) 
        self.QR_l.setMaximumHeight(220) 
        self.QR_l.setMaximumWidth(220)  
        self.lineEdit.textChanged.connect(self.changed)  
        self.apply_btn.clicked.connect(self.changed) 
        self.pushButton_4.clicked.connect(self.changed) 
        self.savecode_btn.clicked.connect(self.write) 
        self.browse_btn.clicked.connect(self.browse) 
        self.browse_logo_btn.clicked.connect(self.browse_logo)
        if self.file_name_lineedit.text()!="": 
                self.savecode_btn.setEnabled(1) 
        else:
                self.savecode_btn.setEnabled(0)  
    def browse(self): 
        fname=QtWidgets.QFileDialog.getExistingDirectory(None, 'Select Folder', "C:/")
        self.file_location_lineedit.setText(fname) 
        self.file_location_lineedit.setReadOnly(1) 
    def browse_logo(self): 
        file , check = QtWidgets.QFileDialog.getOpenFileName(None, "QFileDialog.getOpenFileName()",
                                        "", "All Files (*);;Text Files (*.txt);;Images (*.jpg *png)")
        if check:  
                self.logo_path_linedit.setText(file) 
                self.logo_path_linedit.setReadOnly(1)
                    
    def filecontent(self): 
            self.stackedWidget.setCurrentIndex(1)
    def websitepage(self): 
            self.stackedWidget.setCurrentIndex(0)

    def textmessage(self): 
            self.stackedWidget.setCurrentIndex(3)
    def settings(self): 
            self.stackedWidget.setCurrentIndex(2)
    def update_settings(self): 
        self.label_13.setText(str(self.horizontalSlider_version.value()))
        self.label_14.setText(str(self.horizontalSlider_2_border.value())) 
        self.label_15.setText(str(self.horizontalSlider_3_boxs.value())) 
    def dummy_img(self):
                pixmap=QtGui.QPixmap("down.png") 
                self.QR_l.setPixmap(pixmap) 
                self.QR_l.setScaledContents(1)
    def changed(self):
                if self.stackedWidget.currentIndex()==0: 
                        if self.lineEdit.text()!="":
                                self.image(self.lineEdit.text())
                        else: 
                                self.dummy_img() 
                                self.savecode_btn.setEnabled(0) 
                if self.stackedWidget.currentIndex()==1: 
                        if self.lineEdit_2.text()!="": 
                                try: 
                                        with open(self.lineEdit_2.text(),"r") as f: 
                                                data=f.read()
                                        self.image(data) 
                                except:   
                                        print("file not found")
                                        self.dummy_img()
                                        self.savecode_btn.setEnabled(0)  
                        else :
                                self.dummy_img()
                                self.savecode_btn.setEnabled(0)  
                if self.stackedWidget.currentIndex()==3: 
                        if self.textEdit.toPlainText()!="": 
                                data=self.textEdit.toPlainText() 
                                self.image(data) 
                        else :
                                self.dummy_img()
                                self.savecode_btn.setEnabled(0)  
    def with_out(self,data): 
                qr = qrcode.QRCode(
                version=self.horizontalSlider_version.value(),
                error_correction=qrcode.constants.ERROR_CORRECT_H,
                box_size=self.horizontalSlider_3_boxs.value(),
                border=self.horizontalSlider_2_border.value()
                )
                qr.add_data(data)
                qr.make() 
                try:
                        img = qr.make_image(fill_color=self.fill_lineedit.text(), back_color=self.back_lineedit.text()) 
                 
                except: 
                        img = qr.make_image(fill_color="white", back_color="rgb(0,0,72)")
                img.save('temp_png.png') 
                img.save('temp_jpg.jpg') 
                if self.radio_jpg.isEnabled(): 
                        pixmap=QtGui.QPixmap("temp_jpg.jpg") 
                        self.QR_l.setPixmap(pixmap) 
                        self.QR_l.setScaledContents(1) 
                        if self.file_name_lineedit.text()!="": 
                                self.savecode_btn.setEnabled(1)
        
                if self.radio_png.isEnabled(): 
                        pixmap=QtGui.QPixmap("temp_png.png") 
                        self.QR_l.setPixmap(pixmap) 
                        self.QR_l.setScaledContents(1)  
                        if self.file_name_lineedit.text()!="": 
                                self.savecode_btn.setEnabled(1) 

    def save_code(self):
                if self.radio_jpg.isEnabled():  
                        return "jpg"

                if self.radio_png.isEnabled(): 
                        return "png" 
    def write(self):  
            ty=self.save_code() 
            try:
                if ty=="jpg": 
                        src=r"D:\UI\sample\QR_IP"+"\\"+"temp_jpg.jpg" 
                        des=self.file_location_lineedit.text()+"\\"+"temp_jpg.jpg" 
                        try:
                                shutil.copy(src,des) 
                        except: 
                                print("same location") 
                        try:
                                os.rename(des,self.file_location_lineedit.text()+"\\"+self.file_name_lineedit.text()+".jpg")
                        except:  
                                if self.file_name_lineedit.text()!="":
                                        print("name already exists")
            except: 
                    pass 
                
                                        
                       
    def with_image(self,data):

        # taking image which user wants
        # in the QR code center
        Logo_link = self.logo_path_linedit.text()

        logo = Image.open(Logo_link)

        # taking base width
        basewidth = 100

        # adjust image size
        wpercent = (basewidth/float(logo.size[0]))
        hsize = int((float(logo.size[1])*float(wpercent)))
        logo = logo.resize((basewidth, hsize), Image.ANTIALIAS)
        QRcode = qrcode.QRCode(
                error_correction=qrcode.constants.ERROR_CORRECT_H
        )

        # taking url or text

        # adding URL or text to QRcode
        QRcode.add_data(data)

        # generating QR code
        QRcode.make()

        # taking color name from user
        QRcolor_fill=self.fill_lineedit.text() 
        QRcolor_back=self.back_lineedit.text()

        # adding color to QR code 
        try:
                QRimg = QRcode.make_image(
                        fill_color=QRcolor_fill, back_color=QRcolor_back).convert('RGB')
        except: 
                QRimg = QRcode.make_image(
                        fill_color="white", back_color="rgb(0,0,72)").convert('RGB')

        # set size of QR code
        pos = ((QRimg.size[0] - logo.size[0]) // 2,
                (QRimg.size[1] - logo.size[1]) // 2)
        QRimg.paste(logo, pos)

        # save the QR code generated
        QRimg.save('temp_png.png') 
        QRimg.save('temp_jpg.jpg')
        if self.radio_jpg.isEnabled(): 
                pixmap=QtGui.QPixmap("temp_jpg.jpg") 
                self.QR_l.setPixmap(pixmap) 
                self.QR_l.setScaledContents(1) 

        if self.radio_png.isEnabled(): 
                pixmap=QtGui.QPixmap("temp_png.png") 
                self.QR_l.setPixmap(pixmap) 
                self.QR_l.setScaledContents(1) 




    def image(self,data):  
                try:
                        if self.logo_path_linedit.text()!="": 
                                # with logo program 
                                self.with_image(data)
                                if self.file_name_lineedit.text()!="": 
                                        self.savecode_btn.setEnabled(1)
                        else: 
                                self.with_out(data)
                                if self.file_name_lineedit.text()!="": 
                                        self.savecode_btn.setEnabled(1)

                except: 
                        self.with_out(data)
                        if self.file_name_lineedit.text()!="": 
                                self.savecode_btn.setEnabled(1)


        
                        


         

    
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "QR Genarator"))
        self.pushButton.setText(_translate("MainWindow", "Website"))
        self.pushButton_2.setText(_translate("MainWindow", "File Content"))
        self.pushButton_3.setText(_translate("MainWindow", "Text Message"))
        self.pushButton_5.setText(_translate("MainWindow", "settings"))
        self.label_7.setText(_translate("MainWindow", "Enter Your Website URL "))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Your QR code Will Be Genarated Automatically"))
        self.label_8.setText(_translate("MainWindow", "Enter Your File URL"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "enter file location and click apply"))
        self.label_10.setText(_translate("MainWindow", "Version"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "Border"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "Box Size"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "Genarate"))
        self.QR_l.setText(_translate("MainWindow", "SAMPLE IMAGE IS ALWAYS SAVED"))
        self.label_2.setText(_translate("MainWindow", "File Name"))
        self.file_name_lineedit.setPlaceholderText(_translate("MainWindow", "name only"))
        self.label_3.setText(_translate("MainWindow", "File Location"))
        self.file_location_lineedit.setPlaceholderText(_translate("MainWindow", "location"))
        self.browse_btn.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "FILL"))
        self.fill_lineedit.setPlaceholderText(_translate("MainWindow", "fill color"))
        self.label_5.setText(_translate("MainWindow", "BACK"))
        self.back_lineedit.setPlaceholderText(_translate("MainWindow", "back color"))
        self.apply_btn.setText(_translate("MainWindow", "Apply"))
        self.label_6.setText(_translate("MainWindow", "Logo Path"))
        self.logo_path_linedit.setPlaceholderText(_translate("MainWindow", "logo path"))
        self.browse_logo_btn.setText(_translate("MainWindow", "Browse"))
        self.radio_png.setText(_translate("MainWindow", "PNG"))
        self.radio_jpg.setText(_translate("MainWindow", "JPG"))
        self.radio_svg.setText(_translate("MainWindow", "SVG"))
        self.savecode_btn.setText(_translate("MainWindow", "Save Code"))
  

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
